version: "3"

services:
    main:
        container_name: koa_test_main
        build: ./
        ports:
            - '3000:3000'
        command: sh -c "npm install && npm run dev"
        volumes:
            - ./:/var/www/html/src
    mongoDB:
        image: mongo:latest
        ports:
            - "27017:27017"

